(deftheme xiomacs "Remix of the default emacs color theme.")

(apply 'custom-theme-set-faces 
 '(xiomacs
 (default ((t (:stipple nil :background "cornsilk" :foreground "gray10" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal ))))
 (bg:erc-color-face0 ((t (:background "White"))))
 (bg:erc-color-face1 ((t (:background "black"))))
 (bg:erc-color-face10 ((t (:background "lightblue1"))))
 (bg:erc-color-face11 ((t (:background "cyan"))))
 (bg:erc-color-face12 ((t (:background "blue"))))
 (bg:erc-color-face13 ((t (:background "deeppink"))))
 (bg:erc-color-face14 ((t (:background "gray50"))))
 (bg:erc-color-face15 ((t (:background "gray90"))))
 (bg:erc-color-face2 ((t (:background "blue4"))))
 (bg:erc-color-face3 ((t (:background "green4"))))
 (bg:erc-color-face4 ((t (:background "red"))))
 (bg:erc-color-face5 ((t (:background "brown"))))
 (bg:erc-color-face6 ((t (:background "purple"))))
 (bg:erc-color-face7 ((t (:background "orange"))))
 (bg:erc-color-face8 ((t (:background "yellow"))))
 (bg:erc-color-face9 ((t (:background "green"))))
 (bold ((t (:bold t :weight bold))))
 (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
 (border ((t (nil))))
 (buffer-menu-buffer ((t (:bold t :weight bold))))
 (button ((t (:bold t :background "#f6f5ef" :weight bold))))
 (calendar-today ((t (:underline t))))
 (change-log-acknowledgement ((t (:italic t :slant italic :foreground "#aea79f"))))
 (change-log-conditionals ((t (:foreground "#8b005a"))))
 (change-log-date ((t (:foreground "#dd1144"))))
 (change-log-email ((t (:foreground "#8b005a"))))
 (change-log-file ((t (:bold t :weight bold :foreground "#860e73"))))
 (change-log-function ((t (:foreground "#8b005a"))))
 (change-log-list ((t (:bold t :weight bold :foreground "#f47321"))))
 (change-log-name ((t (:foreground "#f68d47"))))
 (comint-highlight-input ((t (:bold t :weight bold))))
 (comint-highlight-prompt ((t (:foreground "dark blue"))))
 (completions-annotations ((t (:italic t :slant italic))))
 (completions-common-part ((t (:family "DejaVu Sans" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 78))))
 (completions-first-difference ((t (:bold t :weight bold))))
 (cursor ((t (:background "magenta" :foreground "cyan"))))
 (diary ((t (:foreground "red1"))))
 (diary-anniversary ((t (:bold t :weight bold :foreground "#f47321"))))
 (diary-button ((t (nil))))
 (diary-time ((t (:foreground "#8b005a"))))
 (diff-added ((t (nil))))
 (diff-changed ((t (nil))))
 (diff-context ((t (:foreground "grey50"))))
 (diff-file-header ((t (:bold t :background "grey70" :weight bold))))
 (diff-function ((t (:background "grey80"))))
 (diff-header ((t (:background "grey80"))))
 (diff-hunk-header ((t (:background "grey80"))))
 (diff-index ((t (:bold t :weight bold :background "grey70"))))
 (diff-indicator-added ((t (nil))))
 (diff-indicator-changed ((t (nil))))
 (diff-indicator-removed ((t (nil))))
 (diff-nonexistent ((t (:bold t :weight bold :background "grey70"))))
 (diff-refine-change ((t (:background "grey85"))))
 (diff-removed ((t (nil))))
 (dired-directory ((t (:bold t :weight bold :foreground "#860e73"))))
 (dired-flagged ((t (:bold t :weight bold :foreground "#cc0000"))))
 (dired-header ((t (:foreground "#83a525"))))
 (dired-ignored ((t (:foreground "grey50"))))
 (dired-mark ((t (:foreground "#f68d47"))))
 (dired-marked ((t (:bold t :weight bold :foreground "#cc0000"))))
 (dired-perm-write ((t (:italic t :foreground "#aea79f" :slant italic))))
 (dired-symlink ((t (:bold t :weight bold :foreground "#f47321"))))
 (dired-warning ((t (:bold t :weight bold :foreground "#cc0000"))))
 (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
 (ellipsis-face ((t (:bold t :background "blue" :foreground "yellow" :weight bold))))
 (erc-action-face ((t (:bold t :weight bold))))
 (erc-bold-face ((t (:bold t :weight bold))))
 (erc-command-indicator-face ((t (:bold t :weight bold))))
 (erc-current-nick-face ((t (:foreground "white" :background "LightSlateBlue" ))))
 (erc-default-face ((t (:foreground "black"))))
 (erc-direct-msg-face ((t (:foreground "IndianRed"))))
 (erc-error-face ((t (:foreground "red"))))
 (erc-header-line ((t (:background "grey90" :foreground "grey20"))))
 (erc-input-face ((t (:foreground "gray20"))))
 (erc-inverse-face ((t (:background "Black" :foreground "White"))))
 (erc-my-nick-face ((t (:bold t :foreground "brown" :weight bold))))
 (erc-nick-default-face ((t (:foreground "orange" :bold t :weight bold))))
 (erc-nick-msg-face ((t (:bold t :foreground "gray40" bold))))
 (erc-notice-face ((t (:bold t :foreground "SlateBlue" :weight bold))))
 (erc-prompt-face ((t (:bold t :background "lightBlue2" :foreground "Black" :weight bold))))
 (erc-underline-face ((t (:underline t))))
 (escape-glyph ((t (:foreground "brown"))))
 (fg:erc-color-face0 ((t (:foreground "White"))))
 (fg:erc-color-face1 ((t (:foreground "black"))))
 (fg:erc-color-face10 ((t (:foreground "lightblue1"))))
 (fg:erc-color-face11 ((t (:foreground "cyan"))))
 (fg:erc-color-face12 ((t (:foreground "blue"))))
 (fg:erc-color-face13 ((t (:foreground "deeppink"))))
 (fg:erc-color-face14 ((t (:foreground "gray50"))))
 (fg:erc-color-face15 ((t (:foreground "gray90"))))
 (fg:erc-color-face2 ((t (:foreground "blue4"))))
 (fg:erc-color-face3 ((t (:foreground "green4"))))
 (fg:erc-color-face4 ((t (:foreground "red"))))
 (fg:erc-color-face5 ((t (:foreground "brown"))))
 (fg:erc-color-face6 ((t (:foreground "purple"))))
 (fg:erc-color-face7 ((t (:foreground "orange"))))
 (fg:erc-color-face8 ((t (:foreground "yellow"))))
 (fg:erc-color-face9 ((t (:foreground "green"))))
 (file-name-shadow ((t (:foreground "grey50"))))
 (fixed-pitch ((t (:family "Monospace"))))
 (font-lock-builtin-face ((t (:foreground "pale violet red"))))
 (font-lock-comment-delimiter-face ((t (:italic t :slant italic :foreground "gray60" :background "cornsilk"))))
 (font-lock-comment-face ((t (:italic t :foreground "gray50" :background "cornsilk":slant italic))))
 (font-lock-constant-face ((t (:foreground "#f68d47"))))
 (font-lock-doc-face ((t (:foreground "#dd1144"))))
 (font-lock-function-name-face ((t (:bold t :foreground "medium purple" :weight normal))))
 (font-lock-keyword-face ((t (:bold t :foreground "#f47321" :weight normal))))
 (font-lock-negation-char-face ((t (nil))))
 (font-lock-preprocessor-face ((t (:foreground "#62124b"))))
 (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
 (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
 (font-lock-string-face ((t (:foreground "MistyRose4"))))
 (font-lock-type-face ((t (:foreground "#83a525"))))
 (font-lock-variable-name-face ((t (:foreground "orchid" :bold t :weight normal))))
 (font-lock-warning-face ((t (:bold t :foreground "#cc0000" :weight bold))))
 (fringe ((t (:background "wheat"))))
 (header-line ((t (:background "cornsilk" :foreground "yellow green" :bold t :weight bold))))
 (help-argument-name ((t (:italic t :slant italic))))
 (highlight ((t (:background "darkseagreen2"))))
 (holiday ((t (:background "pink"))))
 (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "brown"))))
 (info-header-xref ((t (:foreground "#0086b3" :underline t))))
 (info-menu-header ((t (:bold t :family "Sans Serif" :weight bold))))
 (info-menu-star ((t (:foreground "red1"))))
 (info-node ((t (:italic t :bold t :foreground "brown" :slant italic :weight bold))))
 (info-title-1 ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
 (info-title-2 ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
 (info-title-3 ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
 (info-title-4 ((t (:bold t :family "Sans Serif" :weight bold))))
 (info-xref ((t (:underline t :foreground "#0086b3"))))
 (info-xref-visited ((t (:underline t :foreground "#800080"))))
 (isearch ((t (:background "#fedfc7" :foreground "#333333"))))
 (isearch-fail ((t (:background "RosyBrown1"))))
 (iswitchb-current-match ((t (:bold t :weight bold :background "magenta" :foreground "cyan"))))
 (iswitchb-invalid-regexp ((t (:bold t :weight bold :foreground "#cc0000"))))
 (iswitchb-single-match ((t (:italic t :slant italic :foreground "#aea79f"))))
 (iswitchb-virtual-matches ((t (:foreground "#62124b"))))
 (italic ((t (:italic t :slant italic))))
 (lazy-highlight ((t (:background "#f6f5ef"))))
 (link ((t (:foreground "#0086b3" :underline t))))
 (link-visited ((t (:foreground "#800080" :underline t))))
 (magit-branch ((t (:bold t :weight bold))))
 (magit-diff-add ((t (:foreground "blue1"))))
 (magit-diff-del ((t (:foreground "red"))))
 (magit-diff-file-header ((t (nil))))
 (magit-diff-hunk-header ((t (:italic t :slant italic))))
 (magit-diff-none ((t (nil))))
 (magit-header ((t (nil))))
 (magit-item-highlight ((t (:background "gray95"))))
 (magit-item-mark ((t (:foreground "red"))))
 (magit-log-head-label ((t (:background "spring green"))))
 (magit-log-tag-label ((t (:background "LightGoldenRod"))))
 (magit-section-title ((t (:bold t :weight bold))))
 (match ((t (:background "yellow1"))))
 (menu ((t (nil))))
 (minibuffer-prompt ((t (:bold t :foreground "#f47321" :weight bold))))
 (mode-line ((t (:background "DarkSlateBlue"  :foreground "white" :bold t :weight bold))))
 (mode-line-buffer-id ((t ( :foreground "yellow" :bold t :weight bold))))
 (mode-line-emphasis ((t (:bold t :weight bold))))
 (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
 (mode-line-inactive ((t (:background "gray50" :slant italic :foreground "#333333"))))
 (mouse ((t (nil))))
 (next-error ((t (:foreground "#333333" :background "#f6f5ef"))))
 (nobreak-space ((t (:foreground "brown" :underline t))))
 (org-agenda-clocking ((t (:background "yellow1"))))
 (org-agenda-column-dateline ((t (:family "DejaVu Sans Mono" :weight normal :slant normal :underline nil :strike-through nil :background "grey90" :height 122))))
 (org-agenda-current-time ((t (:foreground "DarkGoldenrod"))))
 (org-agenda-date ((t (:foreground "Blue1"))))
 (org-agenda-date-today ((t (:italic t :bold t :foreground "Blue1" :slant italic :weight bold))))
 (org-agenda-date-weekend ((t (:bold t :foreground "Blue1" :weight bold))))
 (org-agenda-diary ((t (:family "DejaVu Sans" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :height 78))))
 (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
 (org-agenda-done ((t (:foreground "ForestGreen"))))
 (org-agenda-restriction-lock ((t (:background "yellow1"))))
 (org-agenda-structure ((t (:foreground "Blue1"))))
 (org-archived ((t (:foreground "grey50"))))
 (org-block ((t (:foreground "grey50"))))
 (org-block-background ((t (nil))))
 (org-block-begin-line ((t (:italic t :foreground "#aea79f" :slant italic))))
 (org-block-end-line ((t (:italic t :foreground "#aea79f" :slant italic))))
 (org-checkbox ((t (:bold t :weight bold))))
 (org-checkbox-statistics-done ((t (:bold t :weight bold :foreground "ForestGreen"))))
 (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "Red1"))))
 (org-clock-overlay ((t (:background "yellow1"))))
 (org-code ((t (:foreground "grey50"))))
 (org-column ((t (:background "wheat" :strike-through nil :underline nil :slant normal :weight normal))))
 (org-column-title ((t (:foreground "yellow green" :underline t))))
 (org-date ((t (:foreground "Purple" :underline t))))
 (org-document-info ((t (:foreground "midnight blue"))))
 (org-document-info-keyword ((t (:foreground "grey50"))))
 (org-document-title ((t (:bold t :foreground "midnight blue" :weight bold :height 1.44))))
 (org-done ((t (:bold t :foreground "dark sea green" :weight bold))))
 (org-drawer ((t (:foreground "Blue1"))))
 (org-ellipsis ((t (:foreground "DarkGoldenrod" :underline t))))
 (org-footnote ((t (:foreground "Purple" :underline t))))
 (org-formula ((t (:foreground "Firebrick"))))
 (org-headline-done ((t (:foreground "RosyBrown"))))
 (org-hide ((t (:foreground "white"))))
 (org-latex-and-export-specials ((t (:foreground "SaddleBrown"))))
 (org-level-1 ((t (:bold t :foreground "LightSlateBlue" :weight bold))))
 (org-level-2 ((t (:foreground "dim gray"))))
 (org-level-3 ((t (:foreground "dark goldenrod" :bold nil :weight normal))))
 (org-level-4 ((t (:foreground "goldenrod"))))
 (org-level-5 ((t (:foreground "#83a525"))))
 (org-level-6 ((t (:foreground "#f68d47"))))
 (org-level-7 ((t (:foreground "#62124b"))))
 (org-level-8 ((t (:foreground "#dd1144"))))
 (org-link ((t (:underline t :foreground "#0086b3"))))
 (org-meta-line ((t (:italic t :slant italic :foreground "#aea79f"))))
 (org-mode-line-clock ((t (:foreground "#333333" :background "#f6f5ef"))))
 (org-mode-line-clock-overrun ((t (:foreground "#333333" :background "red"))))
 (org-property-value ((t (:foreground "peru"))))
 (org-quote ((t (:foreground "grey50"))))
 (org-scheduled ((t (:foreground "DarkGreen"))))
 (org-scheduled-previously ((t (:foreground "Firebrick"))))
 (org-scheduled-today ((t (:foreground "DarkGreen"))))
 (org-sexp-date ((t (:foreground "Purple"))))
 (org-special-keyword ((t (:italic t :slant italic :foreground "dark khaki"))))
 (org-table ((t (:foreground "Blue1"))))
 (org-tag ((t (:bold t :weight bold))))
 (org-target ((t (:underline t))))
 (org-time-grid ((t (:foreground "DarkGoldenrod"))))
 (org-todo ((t (:bold t :foreground "peru"))))
 (org-upcoming-deadline ((t (:foreground "Firebrick"))))
 (org-verbatim ((t (:foreground "grey50"))))
 (org-verse ((t (:foreground "grey50"))))
 (org-warning ((t (:bold t :weight bold :foreground "#cc0000"))))
 (outline-1 ((t (:bold t :weight bold :foreground "#860e73"))))
 (outline-2 ((t (:foreground "#8b005a"))))
 (outline-3 ((t (:bold t :weight bold :foreground "#f47321"))))
 (outline-4 ((t (:italic t :slant italic :foreground "#aea79f"))))
 (outline-5 ((t (:foreground "#83a525"))))
 (outline-6 ((t (:foreground "#f68d47"))))
 (outline-7 ((t (:foreground "#62124b"))))
 (outline-8 ((t (:foreground "#dd1144"))))
 (query-replace ((t (:foreground "#333333" :background "#fedfc7"))))
 (region ((t (:background "hotpink" :foreground "cyan"))))
 (scroll-bar ((t (nil))))
 (secondary-selection ((t (:background "yellow1"))))
 (sgml-namespace ((t (:foreground "#62124b"))))
 (shadow ((t (:foreground "grey50"))))
 (show-paren-match ((t (:background "turquoise"))))
 (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
 (sldb-catch-tag-face ((t (nil))))
 (sldb-condition-face ((t (nil))))
 (sldb-detailed-frame-line-face ((t (nil))))
 (sldb-frame-label-face ((t (nil))))
 (sldb-frame-line-face ((t (nil))))
 (sldb-local-name-face ((t (nil))))
 (sldb-local-value-face ((t (nil))))
 (sldb-non-restartable-frame-line-face ((t (nil))))
 (sldb-reference-face ((t (:underline t))))
 (sldb-restart-face ((t (nil))))
 (sldb-restart-number-face ((t (:bold t :weight bold))))
 (sldb-restart-type-face ((t (:bold t :weight bold :foreground "#f47321"))))
 (sldb-restartable-frame-line-face ((t (:foreground "lime green"))))
 (sldb-section-face ((t (nil))))
 (sldb-topline-face ((t (nil))))
 (slime-error-face ((t (:underline "red"))))
 (slime-highlight-face ((t (:background "darkseagreen2" :underline nil))))
 (slime-inspector-action-face ((t (:bold t :weight bold :foreground "#cc0000"))))
 (slime-inspector-label-face ((t (:foreground "#f68d47"))))
 (slime-inspector-topline-face ((t (nil))))
 (slime-inspector-type-face ((t (:foreground "#83a525"))))
 (slime-inspector-value-face ((t (:foreground "#62124b"))))
 (slime-note-face ((t (:underline "brown4"))))
 (slime-reader-conditional-face ((t (:italic t :slant italic :foreground "magenta"))))
 (slime-repl-input-face ((t (:bold t :weight bold))))
 (slime-repl-inputed-output-face ((t (:foreground "Red"))))
 (slime-repl-output-face ((t (:foreground "#dd1144"))))
 (slime-repl-output-mouseover-face ((t (:foreground "Red" :box (:line-width 1 :color "black" :style released-button)))))
 (slime-repl-prompt-face ((t (:bold t :weight bold :foreground "#f47321"))))
 (slime-repl-result-face ((t (nil))))
 (slime-style-warning-face ((t (:underline "brown"))))
 (slime-warning-face ((t (:underline "orange"))))
 (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
 (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
 (trailing-whitespace ((t (:background "red1"))))
 (underline ((t (:underline t))))
 (variable-pitch ((t (:family "Sans Serif"))))
 (vertical-border ((t (nil))))
 (widget-button ((t (:bold t :weight bold))))
 (widget-button-pressed ((t (:foreground "red1"))))
 (widget-documentation ((t (:foreground "dark green"))))
 (widget-field ((t (:background "gray85"))))
 (widget-inactive ((t (:foreground "grey50"))))
 (widget-single-line-field ((t (:background "gray85"))))))

(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'xiomacs)
